Repository stackrox/scanner, pull requests merged in 2025-05, with the labels that each got.

#1868 ROX-20312: Pin base image digests and extend Renovate config
  .github/renovate.json5
  image/db/rhel/konflux.Dockerfile
  image/scanner/rhel/konflux.Dockerfile
Labels: konflux-build, backport-for-4.6-konflux-release, backport-for-4.7-konflux-release

#1865 ROX-27638, ROX-20234: Prefetch RPMs, use hermetic builds
  .tekton/scanner-build.yaml
  .tekton/scanner-component-pipeline.yaml
  .tekton/scanner-db-build.yaml
  .tekton/scanner-db-slim-build.yaml
  .tekton/scanner-slim-build.yaml
  image/db/rhel/konflux.Dockerfile
  image/scanner/rhel/konflux.Dockerfile
  rpms.in.yaml
  rpms.lock.yaml
  rpms.ubi.repo
Labels: backport-for-4.6-konflux-release, backport-for-4.7-konflux-release

#1872 ROX-27638: Add docs link to `rpms.in.yaml`
  rpms.in.yaml
Labels: konflux-build, backport-for-4.6-konflux-release, backport-for-4.7-konflux-release

#1875 ROX-29108: Enable `rpm` lockfile renovation
  .github/renovate.json5
Labels: backport-for-4.6-konflux-release, backport-for-4.7-konflux-release

#1876 ROX-20234: Switch scanner rpm prefetch from UBI to RHEL repos
  .tekton/scanner-component-pipeline.yaml
  image/scanner/rhel/konflux.Dockerfile
  rpms.in.yaml
  rpms.lock.yaml
  rpms.rhel.repo
  rpms.ubi.repo
Labels: konflux-build, backport-for-4.6-konflux-release, backport-for-4.7-konflux-release

#1880 ROX-29108: Induce RPM lockfile renovation
  rpms.lock.yaml
Labels: konflux-build

#1883 fix(ci): increase timeout processing RH OVAL data
  ext/vulnsrc/rhel/rhel.go
Labels: generate-dumps-on-pr

#1891 ROX-29078: switch to per component SA
  .tekton/scanner-build.yaml
  .tekton/scanner-db-build.yaml
  .tekton/scanner-db-slim-build.yaml
  .tekton/scanner-slim-build.yaml
Labels: konflux-build, backport-for-4.6-konflux-release, backport-for-4.7-konflux-release

#1881 ROX-28568: Add required tasks sast-shell-check and sast-unicode-check to Konflux pipelines
  .tekton/scanner-component-pipeline.yaml
Labels: backport-for-4.6-konflux-release, backport-for-4.7-konflux-release

#1906 ROX-29479: Change Scanner V2 repos for Konflux builds
  .tekton/scanner-build.yaml
  .tekton/scanner-db-build.yaml
  .tekton/scanner-db-slim-build.yaml
  .tekton/scanner-slim-build.yaml
Labels: backport-for-4.6-konflux-release, backport-for-4.7-konflux-release
