Repository stackrox/scanner, pull requests merged in 2025-01, with the labels that each got.

#1751 ROX-27480: Use new revision of the fetch task
  .konflux/scripts/fetch-scanner-data.sh
  .tekton/scanner-component-pipeline.yaml
Labels: konflux-build, backport-for-4.6-konflux-release

#1762 chore: Kill `Java` mentions from Konflux pipelines
  .tekton/scanner-component-pipeline.yaml
Labels: backport-for-4.6-konflux-release

#1763 ROX-24530: let Konflux images expire after 13w
  .tekton/scanner-build.yaml
  .tekton/scanner-db-build.yaml
  .tekton/scanner-db-slim-build.yaml
  .tekton/scanner-slim-build.yaml
Labels: backport-for-4.6-konflux-release

#1709 ROX-24283: enable strictfipsruntime in the Konflux build
  Makefile
  image/scanner/rhel/konflux.Dockerfile
Labels: konflux-build

#1766 ROX-26604: Backport lineage fix to ACS 4.6.x (Scanner 2.35.x)
  Makefile
  api/v1/models.go
  api/v1/models_rhelv2.go
  api/v1/models_rhelv2_test.go
  database/database.go
  database/mock.go
  database/models.go
  database/pgsql/migrations/00021_rhel_layer_lineage.go
  database/pgsql/queries.go
  database/pgsql/rhelv2_layer.go
  database/pgsql/rhelv2_layer_test.go
  e2etests/node_scan_rhcos_test.go
  e2etests/sanity_test.go
  e2etests/testcase_test.go
  pkg/env/list.go
  worker.go
Labels: generate-dumps-on-pr

#1771 ROX-27384: Use the updated `determine-image-tag` task
  .konflux/scripts/fail-build-if-git-is-dirty.sh
  .tekton/scanner-build.yaml
  .tekton/scanner-component-pipeline.yaml
  .tekton/scanner-db-build.yaml
  .tekton/scanner-db-slim-build.yaml
  .tekton/scanner-slim-build.yaml
  image/scanner/rhel/konflux.Dockerfile
Labels: backport-for-4.6-konflux-release

#1784 Bump max known OCP version
  pkg/cpeutils/utils.go
  pkg/cpeutils/utils_test.go
Labels: generate-dumps-on-pr
