Repository stackrox/scanner, pull requests merged in 2025-02, with the labels that each got.

#1795 hardcode OpenShift CPEs
  pkg/cpeutils/utils.go
  pkg/cpeutils/utils_test.go
Labels: generate-dumps-on-pr

#1811 chore: bump genesis
  image/scanner/dump/genesis_manifests.json
Labels: generate-dumps-on-pr

#1806 ROX-27831: set image expiration based on event type and target branch
  .tekton/scanner-component-pipeline.yaml
Labels: backport-for-4.6-konflux-release

#1819 ROX-27905: Exclude example rpmdb from SBOMs
  .github/workflows/ci.yaml
  .syft.yaml
  scripts/ci/jobs/check-konflux-setup.sh
Labels: konflux-build, backport-for-4.6-konflux-release, backport-for-4.7-konflux-release
